# Generated by Django 3.2.6 on 2022-01-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20220112_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bucket',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
